//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetInventoryClientList
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://gpjws.gpjco.com/GetInventoryClientList", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://gpjws.gpjco.com/GetInventoryClientList", ConfigurationName="GetInventoryClientList.GetInventoryClientListSoap")]
    public interface GetInventoryClientListSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://gpjws.gpjco.com/GetInventoryClientList/GetClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<GetInventoryClientList.GetClientListResponse> GetClientListAsync(GetInventoryClientList.GetClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://gpjws.gpjco.com/GetInventoryClientList/GetClientList_Company10", ReplyAction="*")]
        System.Threading.Tasks.Task<GetInventoryClientList.GetClientList_Company10Response> GetClientList_Company10Async(GetInventoryClientList.GetClientList_Company10Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientList", Namespace="https://gpjws.gpjco.com/GetInventoryClientList", Order=0)]
        public GetInventoryClientList.GetClientListRequestBody Body;
        
        public GetClientListRequest()
        {
        }
        
        public GetClientListRequest(GetInventoryClientList.GetClientListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gpjws.gpjco.com/GetInventoryClientList")]
    public partial class GetClientListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long pGroupID;
        
        public GetClientListRequestBody()
        {
        }
        
        public GetClientListRequestBody(long pGroupID)
        {
            this.pGroupID = pGroupID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientListResponse", Namespace="https://gpjws.gpjco.com/GetInventoryClientList", Order=0)]
        public GetInventoryClientList.GetClientListResponseBody Body;
        
        public GetClientListResponse()
        {
        }
        
        public GetClientListResponse(GetInventoryClientList.GetClientListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gpjws.gpjco.com/GetInventoryClientList")]
    public partial class GetClientListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClientListResult;
        
        public GetClientListResponseBody()
        {
        }
        
        public GetClientListResponseBody(string GetClientListResult)
        {
            this.GetClientListResult = GetClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientList_Company10Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientList_Company10", Namespace="https://gpjws.gpjco.com/GetInventoryClientList", Order=0)]
        public GetInventoryClientList.GetClientList_Company10RequestBody Body;
        
        public GetClientList_Company10Request()
        {
        }
        
        public GetClientList_Company10Request(GetInventoryClientList.GetClientList_Company10RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gpjws.gpjco.com/GetInventoryClientList")]
    public partial class GetClientList_Company10RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetInventoryClientList.ArrayOfString pENVIRONMENT;
        
        public GetClientList_Company10RequestBody()
        {
        }
        
        public GetClientList_Company10RequestBody(GetInventoryClientList.ArrayOfString pENVIRONMENT)
        {
            this.pENVIRONMENT = pENVIRONMENT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientList_Company10Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientList_Company10Response", Namespace="https://gpjws.gpjco.com/GetInventoryClientList", Order=0)]
        public GetInventoryClientList.GetClientList_Company10ResponseBody Body;
        
        public GetClientList_Company10Response()
        {
        }
        
        public GetClientList_Company10Response(GetInventoryClientList.GetClientList_Company10ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gpjws.gpjco.com/GetInventoryClientList")]
    public partial class GetClientList_Company10ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetInventoryClientList.ArrayOfString GetClientList_Company10Result;
        
        public GetClientList_Company10ResponseBody()
        {
        }
        
        public GetClientList_Company10ResponseBody(GetInventoryClientList.ArrayOfString GetClientList_Company10Result)
        {
            this.GetClientList_Company10Result = GetClientList_Company10Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetInventoryClientListSoapChannel : GetInventoryClientList.GetInventoryClientListSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetInventoryClientListSoapClient : System.ServiceModel.ClientBase<GetInventoryClientList.GetInventoryClientListSoap>, GetInventoryClientList.GetInventoryClientListSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetInventoryClientListSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GetInventoryClientListSoapClient.GetBindingForEndpoint(endpointConfiguration), GetInventoryClientListSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInventoryClientListSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetInventoryClientListSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInventoryClientListSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetInventoryClientListSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInventoryClientListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetInventoryClientList.GetClientListResponse> GetInventoryClientList.GetInventoryClientListSoap.GetClientListAsync(GetInventoryClientList.GetClientListRequest request)
        {
            return base.Channel.GetClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetInventoryClientList.GetClientListResponse> GetClientListAsync(long pGroupID)
        {
            GetInventoryClientList.GetClientListRequest inValue = new GetInventoryClientList.GetClientListRequest();
            inValue.Body = new GetInventoryClientList.GetClientListRequestBody();
            inValue.Body.pGroupID = pGroupID;
            return ((GetInventoryClientList.GetInventoryClientListSoap)(this)).GetClientListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetInventoryClientList.GetClientList_Company10Response> GetInventoryClientList.GetInventoryClientListSoap.GetClientList_Company10Async(GetInventoryClientList.GetClientList_Company10Request request)
        {
            return base.Channel.GetClientList_Company10Async(request);
        }
        
        public System.Threading.Tasks.Task<GetInventoryClientList.GetClientList_Company10Response> GetClientList_Company10Async(GetInventoryClientList.ArrayOfString pENVIRONMENT)
        {
            GetInventoryClientList.GetClientList_Company10Request inValue = new GetInventoryClientList.GetClientList_Company10Request();
            inValue.Body = new GetInventoryClientList.GetClientList_Company10RequestBody();
            inValue.Body.pENVIRONMENT = pENVIRONMENT;
            return ((GetInventoryClientList.GetInventoryClientListSoap)(this)).GetClientList_Company10Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetInventoryClientListSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GetInventoryClientListSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetInventoryClientListSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://gpjws.gpjco.com/GetInventoryClientList/GetInventoryClientList.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GetInventoryClientListSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://gpjws.gpjco.com/GetInventoryClientList/GetInventoryClientList.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GetInventoryClientListSoap,
            
            GetInventoryClientListSoap12,
        }
    }
}
